name: auto build and auto release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
          retention-days: 1

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "$v.{{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "$v.{{ github.run_number }}"
          title: "Automated Build $v.{{ github.run_number }}"
          prerelease: true
          files: target/*.jar